import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'bg-primary')}>
        <div className="fixed top-0 right-0 bg h-screen">
          <img src="./bg.png" alt="" className="h-full" />
        </div>
        {children}
      </body>
    </html>
  );
}
